export const darkMapStyle = [
  { elementType: "geometry", stylers: [{ color: "#1c1c1e" }] },
  { elementType: "labels.icon", stylers: [{ visibility: "off" }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#8e8e93" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#1c1c1e" }] },
  { featureType: "administrative", elementType: "geometry", stylers: [{ color: "#3a3a3c" }] },
  { featureType: "administrative.country", elementType: "labels.text.fill", stylers: [{ color: "#aeaeb2" }] },
  { featureType: "administrative.land_parcel", stylers: [{ visibility: "off" }] },
  { featureType: "administrative.locality", elementType: "labels.text.fill", stylers: [{ color: "#c7c7cc" }] },
  { featureType: "poi", elementType: "labels.text.fill", stylers: [{ color: "#8e8e93" }] },
  { featureType: "poi.park", elementType: "geometry", stylers: [{ color: "#121212" }] },
  { featureType: "poi.park", elementType: "labels.text.fill", stylers: [{ color: "#636366" }] },
  { featureType: "poi.park", elementType: "labels.text.stroke", stylers: [{ color: "#121212" }] },
  { featureType: "road", elementType: "geometry.fill", stylers: [{ color: "#2c2c2e" }] },
  { featureType: "road", elementType: "labels.text.fill", stylers: [{ color: "#8e8e93" }] },
  { featureType: "road.arterial", elementType: "geometry", stylers: [{ color: "#3a3a3c" }] },
  { featureType: "road.highway", elementType: "geometry", stylers: [{ color: "#48484a" }] },
  { featureType: "road.highway.controlled_access", elementType: "geometry", stylers: [{ color: "#636366" }] },
  { featureType: "road.local", elementType: "labels.text.fill", stylers: [{ color: "#636366" }] },
  { featureType: "transit", elementType: "labels.text.fill", stylers: [{ color: "#8e8e93" }] },
  { featureType: "water", elementType: "geometry", stylers: [{ color: "#000000" }] },
  { featureType: "water", elementType: "labels.text.fill", stylers: [{ color: "#3a3a3c" }] }
];
